// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdcm8ntEJ89sN-N3hr_EVo5fQIV3sCBU',
    appId: '1:819291291292:web:cecab9dcd981761495f759',
    messagingSenderId: '819291291292',
    projectId: 'ddd6-2fce6',
    authDomain: 'ddd6-2fce6.firebaseapp.com',
    storageBucket: 'ddd6-2fce6.firebasestorage.app',
    measurementId: 'G-5L96DMCZ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_xOhHRFGxltL3uar5BunRivV29zDgAs',
    appId: '1:819291291292:android:2ee13d27cadeb68a95f759',
    messagingSenderId: '819291291292',
    projectId: 'ddd6-2fce6',
    storageBucket: 'ddd6-2fce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRj51BGtK04R54BVWXCHYe7v6gJ8Ig0dc',
    appId: '1:819291291292:ios:c404508ad5ea37c195f759',
    messagingSenderId: '819291291292',
    projectId: 'ddd6-2fce6',
    storageBucket: 'ddd6-2fce6.firebasestorage.app',
    iosBundleId: 'org.',
  );
}
